name: Memory profiler

on:
  issue_comment:                                     
    types: [created, edited]
  
defaults:
  run:
    shell: bash -l {0}

jobs:
  memory-profiler:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/memory_profiler')
    runs-on: [ubuntu-latest]
    steps:    
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-name: pam-ubuntu-latest-311-memray
          environment-file: requirements/base.txt
          create-args: >-
            -c city-modelling-lab
            -f requirements/dev.txt
            python=3.11
            memray
            pytest-memray
          post-cleanup: all
          cache-environment: true

      - name: install PAM
        run: pip install --no-dependencies .

      - name: run memory and time profiling test
        run: pytest -p memray -m "high_mem" --no-cov