name: Build Package

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: bash -l {0}
      
jobs:
  conda-build:
    uses: arup-group/actions-city-modelling-lab/workflows/conda-build.yml@main
    with:
      package_name: pam