name: Build Package

on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash -l {0}
      
jobs:
  conda-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: latest
        environment-name: pam-condabuild
        create-args: >-
            python=3.11
            boa
            conda-verify
        post-cleanup: all
    
    - name: add CML conda channel
      run: conda config --add channels city-modelling-lab

    - name: Create build directory
      run: 
        
    - name: Build conda package
      run: |
        conda mambabuild .
        conda mambabuild purge
        echo "conda_build_dir=$(conda build --output .)" >> $GITHUB_OUTPUT"
      id: build_package

    - name: Test installing built conda package
      run: mamba install --use-local pam

    - name: Upload built conda package ready for upload on release
      uses: actions/upload-artifact@v3
      with:
        name: conda-build-${{ github.ref_name }}
        path: "${{ steps.build_package.output.conda_build_dir }}"
        retention-days: 7