name: Build Package

on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash -l {0}

env: 
  RELEASE_TAG_VERSION: ${{ github.ref_name }}
      
jobs:
  conda-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: latest
        environment-name: pam-condabuild
        create-args: >-
            python=3.11
            boa
        post-cleanup: all
    
    - name: add CML conda channel
      run: conda config --add channels city-modelling-lab

    - name: Build conda package
      run: |
        mkdir ${{ runner.temp }}/conda_builds
        conda mambabuild --output-folder ${{ runner.temp }}/conda_builds .
        conda mambabuild --output .
    
    - name: Upload built conda package ready for upload on release
      uses: actions/upload-artifact@v3
      with:
        name: conda-build-$RELEASE_TAG_VERSION
        path: ${{ runner.temp }}/conda_builds
        retention-days: 7

    - name: Test installing built conda package
      run: micromamba install -c local pam