name: Publish

on:
  release:
    types: [released]
      
jobs:
  conda-upload:
    uses: arup-group/actions-city-modelling-lab/workflows/conda-upload.yml@main
    secrets: inherit
    with:
      package_name: pam
  docs-stable:
    uses: arup-group/actions-city-modelling-lab/workflows/docs-deploy.yml@main
    with:
      deploy_type: update_stable
      notebook_kernel: pam