name: Publish

on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash -l {0}

permissions:
    contents: write

env: 
  RELEASE_TAG_VERSION: ${{ github.ref_name }}
      
jobs:
  conda-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: latest
        environment-name: pam-condabuild
        create-args: >-
            python=3.11
            conda-build
            anaconda-client
        post-cleanup: all
    
    - name: add CML conda channel
      run: conda config --add channels city-modelling-lab

    - name: Build conda package
      run: |
        mkdir ${{ runner.temp }}/conda_builds
        conda build --output-folder ${{ runner.temp }}/conda_builds .
        echo conda build --output .

    - name: Test installing built conda package
      run: micromamba install --use-local pam

    - name: Upload to anaconda
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: anaconda upload ${{ runner.temp }}/conda_builds/noarch/pam*-tar.bz2 --version $RELEASE_TAG_VERSION

  docs-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0  # used to build docs into the gh-pages branch without losing branch history. See https://github.com/jimporter/mike/issues/49

    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: latest
        environment-name: pam-docs
        environment-file: requirements/base.txt
        create-args: >-
            -c city-modelling-lab
            python=3.11
            requirements/docs.txt
        post-cleanup: all
        cache-environment: true

    - name: Setup doc deploy
      run: |
        git config --global user.name Docs deploy
        git config --global user.email docs@dummy.bot.com
        
    - name: deploy docs to gh-pages branch
      run: |
        mike deploy --push --update-aliases $RELEASE_TAG_VERSION latest
        mike set-default --push latest